sudo: required
language: c

env:
  global:
    - INFCLOUD_EXPORT_PATH="/srv/docker/infcloud"

services:
  - docker

install:
  - make build
  - docker run -d -p 80:80 --name infcloud waja/infcloud

script:
  - make test
